/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Centrisportivi;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CentrisportiviRecord extends TableRecordImpl<CentrisportiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CentriSportivi.idCentro</code>.
     */
    public void setIdcentro(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CentriSportivi.idCentro</code>.
     */
    public Integer getIdcentro() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CentriSportivi.nomeCommerciale</code>.
     */
    public void setNomecommerciale(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CentriSportivi.nomeCommerciale</code>.
     */
    public String getNomecommerciale() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CentriSportivi.indirizzo</code>.
     */
    public void setIndirizzo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>CentriSportivi.indirizzo</code>.
     */
    public Integer getIndirizzo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>CentriSportivi.latitudine</code>.
     */
    public void setLatitudine(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CentriSportivi.latitudine</code>.
     */
    public BigDecimal getLatitudine() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>CentriSportivi.longitudine</code>.
     */
    public void setLongitudine(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>CentriSportivi.longitudine</code>.
     */
    public BigDecimal getLongitudine() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>CentriSportivi.credito</code>.
     */
    public void setCredito(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>CentriSportivi.credito</code>.
     */
    public BigDecimal getCredito() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>CentriSportivi.orarioApertura</code>.
     */
    public void setOrarioapertura(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CentriSportivi.orarioApertura</code>.
     */
    public String getOrarioapertura() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CentriSportivi.orarioChiusura</code>.
     */
    public void setOrariochiusura(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CentriSportivi.orarioChiusura</code>.
     */
    public String getOrariochiusura() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CentriSportivi.idGestore</code>.
     */
    public void setIdgestore(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>CentriSportivi.idGestore</code>.
     */
    public Integer getIdgestore() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CentrisportiviRecord
     */
    public CentrisportiviRecord() {
        super(Centrisportivi.CENTRISPORTIVI);
    }

    /**
     * Create a detached, initialised CentrisportiviRecord
     */
    public CentrisportiviRecord(Integer idcentro, String nomecommerciale, Integer indirizzo, BigDecimal latitudine, BigDecimal longitudine, BigDecimal credito, String orarioapertura, String orariochiusura, Integer idgestore) {
        super(Centrisportivi.CENTRISPORTIVI);

        setIdcentro(idcentro);
        setNomecommerciale(nomecommerciale);
        setIndirizzo(indirizzo);
        setLatitudine(latitudine);
        setLongitudine(longitudine);
        setCredito(credito);
        setOrarioapertura(orarioapertura);
        setOrariochiusura(orariochiusura);
        setIdgestore(idgestore);
        resetChangedOnNotNull();
    }
}
