/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Dettaglioservizicentri;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DettaglioservizicentriRecord extends TableRecordImpl<DettaglioservizicentriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DettaglioServiziCentri.idServizio</code>.
     */
    public void setIdservizio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DettaglioServiziCentri.idServizio</code>.
     */
    public Integer getIdservizio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DettaglioServiziCentri.idCentro</code>.
     */
    public void setIdcentro(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DettaglioServiziCentri.idCentro</code>.
     */
    public Integer getIdcentro() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DettaglioservizicentriRecord
     */
    public DettaglioservizicentriRecord() {
        super(Dettaglioservizicentri.DETTAGLIOSERVIZICENTRI);
    }

    /**
     * Create a detached, initialised DettaglioservizicentriRecord
     */
    public DettaglioservizicentriRecord(Integer idservizio, Integer idcentro) {
        super(Dettaglioservizicentri.DETTAGLIOSERVIZICENTRI);

        setIdservizio(idservizio);
        setIdcentro(idcentro);
        resetChangedOnNotNull();
    }
}
