/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Dettagliotipologiecentri;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DettagliotipologiecentriRecord extends TableRecordImpl<DettagliotipologiecentriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DettaglioTipologieCentri.idCentro</code>.
     */
    public void setIdcentro(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DettaglioTipologieCentri.idCentro</code>.
     */
    public Integer getIdcentro() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DettaglioTipologieCentri.idTipologia</code>.
     */
    public void setIdtipologia(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DettaglioTipologieCentri.idTipologia</code>.
     */
    public Integer getIdtipologia() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DettagliotipologiecentriRecord
     */
    public DettagliotipologiecentriRecord() {
        super(Dettagliotipologiecentri.DETTAGLIOTIPOLOGIECENTRI);
    }

    /**
     * Create a detached, initialised DettagliotipologiecentriRecord
     */
    public DettagliotipologiecentriRecord(Integer idcentro, Integer idtipologia) {
        super(Dettagliotipologiecentri.DETTAGLIOTIPOLOGIECENTRI);

        setIdcentro(idcentro);
        setIdtipologia(idtipologia);
        resetChangedOnNotNull();
    }
}
