/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Disponibilita;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DisponibilitaRecord extends TableRecordImpl<DisponibilitaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Disponibilita.idDisponibilita</code>.
     */
    public void setIddisponibilita(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Disponibilita.idDisponibilita</code>.
     */
    public Integer getIddisponibilita() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Disponibilita.dataOra</code>.
     */
    public void setDataora(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Disponibilita.dataOra</code>.
     */
    public String getDataora() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Disponibilita.prezzo</code>.
     */
    public void setPrezzo(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>Disponibilita.prezzo</code>.
     */
    public BigDecimal getPrezzo() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>Disponibilita.tipoCampo</code>.
     */
    public void setTipocampo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Disponibilita.tipoCampo</code>.
     */
    public Integer getTipocampo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Disponibilita.idCentro</code>.
     */
    public void setIdcentro(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Disponibilita.idCentro</code>.
     */
    public Integer getIdcentro() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisponibilitaRecord
     */
    public DisponibilitaRecord() {
        super(Disponibilita.DISPONIBILITA);
    }

    /**
     * Create a detached, initialised DisponibilitaRecord
     */
    public DisponibilitaRecord(Integer iddisponibilita, String dataora, BigDecimal prezzo, Integer tipocampo, Integer idcentro) {
        super(Disponibilita.DISPONIBILITA);

        setIddisponibilita(iddisponibilita);
        setDataora(dataora);
        setPrezzo(prezzo);
        setTipocampo(tipocampo);
        setIdcentro(idcentro);
        resetChangedOnNotNull();
    }
}
