/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Messaggigesorg;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessaggigesorgRecord extends TableRecordImpl<MessaggigesorgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MessaggiGesOrg.idMessaggio</code>.
     */
    public void setIdmessaggio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idMessaggio</code>.
     */
    public Integer getIdmessaggio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MessaggiGesOrg.stato</code>.
     */
    public void setStato(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.stato</code>.
     */
    public Integer getStato() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MessaggiGesOrg.testo</code>.
     */
    public void setTesto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.testo</code>.
     */
    public String getTesto() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MessaggiGesOrg.dataOra</code>.
     */
    public void setDataora(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.dataOra</code>.
     */
    public String getDataora() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MessaggiGesOrg.idGestore</code>.
     */
    public void setIdgestore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idGestore</code>.
     */
    public Integer getIdgestore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MessaggiGesOrg.idOrganizzatore</code>.
     */
    public void setIdorganizzatore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idOrganizzatore</code>.
     */
    public Integer getIdorganizzatore() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessaggigesorgRecord
     */
    public MessaggigesorgRecord() {
        super(Messaggigesorg.MESSAGGIGESORG);
    }

    /**
     * Create a detached, initialised MessaggigesorgRecord
     */
    public MessaggigesorgRecord(Integer idmessaggio, Integer stato, String testo, String dataora, Integer idgestore, Integer idorganizzatore) {
        super(Messaggigesorg.MESSAGGIGESORG);

        setIdmessaggio(idmessaggio);
        setStato(stato);
        setTesto(testo);
        setDataora(dataora);
        setIdgestore(idgestore);
        setIdorganizzatore(idorganizzatore);
        resetChangedOnNotNull();
    }
}
