/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Partite;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PartiteRecord extends TableRecordImpl<PartiteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Partite.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Partite.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Partite.postiTotali</code>.
     */
    public void setPostitotali(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Partite.postiTotali</code>.
     */
    public Integer getPostitotali() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Partite.pubblica</code>.
     */
    public void setPubblica(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Partite.pubblica</code>.
     */
    public Integer getPubblica() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Partite.sato</code>.
     */
    public void setSato(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Partite.sato</code>.
     */
    public Integer getSato() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Partite.modPagamento</code>.
     */
    public void setModpagamento(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Partite.modPagamento</code>.
     */
    public String getModpagamento() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Partite.idOrganizzatore</code>.
     */
    public void setIdorganizzatore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Partite.idOrganizzatore</code>.
     */
    public Integer getIdorganizzatore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Partite.idDisponibilità</code>.
     */
    public void setIddisponibilità(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Partite.idDisponibilità</code>.
     */
    public Integer getIddisponibilità() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>Partite.goalSquadraCasa</code>.
     */
    public void setGoalsquadracasa(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Partite.goalSquadraCasa</code>.
     */
    public Integer getGoalsquadracasa() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Partite.goalSquadraTrasferta</code>.
     */
    public void setGoalsquadratrasferta(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Partite.goalSquadraTrasferta</code>.
     */
    public Integer getGoalsquadratrasferta() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartiteRecord
     */
    public PartiteRecord() {
        super(Partite.PARTITE);
    }

    /**
     * Create a detached, initialised PartiteRecord
     */
    public PartiteRecord(Integer idpartita, Integer postitotali, Integer pubblica, Integer sato, String modpagamento, Integer idorganizzatore, Integer iddisponibilità, Integer goalsquadracasa, Integer goalsquadratrasferta) {
        super(Partite.PARTITE);

        setIdpartita(idpartita);
        setPostitotali(postitotali);
        setPubblica(pubblica);
        setSato(sato);
        setModpagamento(modpagamento);
        setIdorganizzatore(idorganizzatore);
        setIddisponibilità(iddisponibilità);
        setGoalsquadracasa(goalsquadracasa);
        setGoalsquadratrasferta(goalsquadratrasferta);
        resetChangedOnNotNull();
    }
}
