/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Squadre;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SquadreRecord extends TableRecordImpl<SquadreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Squadre.idSquadra</code>.
     */
    public void setIdsquadra(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Squadre.idSquadra</code>.
     */
    public Integer getIdsquadra() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Squadre.nomeSquadra</code>.
     */
    public void setNomesquadra(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Squadre.nomeSquadra</code>.
     */
    public String getNomesquadra() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Squadre.coloreMaglia</code>.
     */
    public void setColoremaglia(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Squadre.coloreMaglia</code>.
     */
    public String getColoremaglia() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Squadre.inCasa</code>.
     */
    public void setIncasa(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Squadre.inCasa</code>.
     */
    public Integer getIncasa() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Squadre.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Squadre.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SquadreRecord
     */
    public SquadreRecord() {
        super(Squadre.SQUADRE);
    }

    /**
     * Create a detached, initialised SquadreRecord
     */
    public SquadreRecord(Integer idsquadra, String nomesquadra, String coloremaglia, Integer incasa, Integer idpartita) {
        super(Squadre.SQUADRE);

        setIdsquadra(idsquadra);
        setNomesquadra(nomesquadra);
        setColoremaglia(coloremaglia);
        setIncasa(incasa);
        setIdpartita(idpartita);
        resetChangedOnNotNull();
    }
}
