/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Tipologiecampo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TipologiecampoRecord extends TableRecordImpl<TipologiecampoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TipologieCampo.idTipologia</code>.
     */
    public void setIdtipologia(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TipologieCampo.idTipologia</code>.
     */
    public Integer getIdtipologia() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TipologieCampo.nomeTipologia</code>.
     */
    public void setNometipologia(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TipologieCampo.nomeTipologia</code>.
     */
    public String getNometipologia() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TipologiecampoRecord
     */
    public TipologiecampoRecord() {
        super(Tipologiecampo.TIPOLOGIECAMPO);
    }

    /**
     * Create a detached, initialised TipologiecampoRecord
     */
    public TipologiecampoRecord(Integer idtipologia, String nometipologia) {
        super(Tipologiecampo.TIPOLOGIECAMPO);

        setIdtipologia(idtipologia);
        setNometipologia(nometipologia);
        resetChangedOnNotNull();
    }
}
