/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables.records;


import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;

import sport_mate_inc.sport_mate_business_layer.tables.Transazioni;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransazioniRecord extends TableRecordImpl<TransazioniRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Transazioni.idTransazione</code>.
     */
    public void setIdtransazione(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Transazioni.idTransazione</code>.
     */
    public Integer getIdtransazione() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Transazioni.importo</code>.
     */
    public void setImporto(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>Transazioni.importo</code>.
     */
    public BigDecimal getImporto() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>Transazioni.data</code>.
     */
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Transazioni.data</code>.
     */
    public String getData() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Transazioni.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Transazioni.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Transazioni.idUtente</code>.
     */
    public void setIdutente(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Transazioni.idUtente</code>.
     */
    public Integer getIdutente() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransazioniRecord
     */
    public TransazioniRecord() {
        super(Transazioni.TRANSAZIONI);
    }

    /**
     * Create a detached, initialised TransazioniRecord
     */
    public TransazioniRecord(Integer idtransazione, BigDecimal importo, String data, Integer idpartita, Integer idutente) {
        super(Transazioni.TRANSAZIONI);

        setIdtransazione(idtransazione);
        setImporto(importo);
        setData(data);
        setIdpartita(idpartita);
        setIdutente(idutente);
        resetChangedOnNotNull();
    }
}
