/*
 * This file is generated by jOOQ.
 */
package sportmateinc.sportmatebusinesslayergenerated;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sportmateinc.sportmatebusinesslayergenerated.tables.Centrisportivi;
import sportmateinc.sportmatebusinesslayergenerated.tables.Dettaglioservizicentri;
import sportmateinc.sportmatebusinesslayergenerated.tables.Dettagliotipologiecentri;
import sportmateinc.sportmatebusinesslayergenerated.tables.Disponibilita;
import sportmateinc.sportmatebusinesslayergenerated.tables.Feedback;
import sportmateinc.sportmatebusinesslayergenerated.tables.Gestori;
import sportmateinc.sportmatebusinesslayergenerated.tables.Livelli;
import sportmateinc.sportmatebusinesslayergenerated.tables.Messaggigesorg;
import sportmateinc.sportmatebusinesslayergenerated.tables.Messaggiorgfin;
import sportmateinc.sportmatebusinesslayergenerated.tables.Partite;
import sportmateinc.sportmatebusinesslayergenerated.tables.Serviziaggiuntivi;
import sportmateinc.sportmatebusinesslayergenerated.tables.Squadre;
import sportmateinc.sportmatebusinesslayergenerated.tables.Tipologiecampo;
import sportmateinc.sportmatebusinesslayergenerated.tables.Transazioni;
import sportmateinc.sportmatebusinesslayergenerated.tables.Utenti;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CentriSportivi</code>.
     */
    public final Centrisportivi CENTRISPORTIVI = Centrisportivi.CENTRISPORTIVI;

    /**
     * The table <code>DettaglioServiziCentri</code>.
     */
    public final Dettaglioservizicentri DETTAGLIOSERVIZICENTRI = Dettaglioservizicentri.DETTAGLIOSERVIZICENTRI;

    /**
     * The table <code>DettaglioTipologieCentri</code>.
     */
    public final Dettagliotipologiecentri DETTAGLIOTIPOLOGIECENTRI = Dettagliotipologiecentri.DETTAGLIOTIPOLOGIECENTRI;

    /**
     * The table <code>Disponibilita</code>.
     */
    public final Disponibilita DISPONIBILITA = Disponibilita.DISPONIBILITA;

    /**
     * The table <code>Feedback</code>.
     */
    public final Feedback FEEDBACK = Feedback.FEEDBACK;

    /**
     * The table <code>Gestori</code>.
     */
    public final Gestori GESTORI = Gestori.GESTORI;

    /**
     * The table <code>Livelli</code>.
     */
    public final Livelli LIVELLI = Livelli.LIVELLI;

    /**
     * The table <code>MessaggiGesOrg</code>.
     */
    public final Messaggigesorg MESSAGGIGESORG = Messaggigesorg.MESSAGGIGESORG;

    /**
     * The table <code>MessaggiOrgFin</code>.
     */
    public final Messaggiorgfin MESSAGGIORGFIN = Messaggiorgfin.MESSAGGIORGFIN;

    /**
     * The table <code>Partite</code>.
     */
    public final Partite PARTITE = Partite.PARTITE;

    /**
     * The table <code>ServiziAggiuntivi</code>.
     */
    public final Serviziaggiuntivi SERVIZIAGGIUNTIVI = Serviziaggiuntivi.SERVIZIAGGIUNTIVI;

    /**
     * The table <code>Squadre</code>.
     */
    public final Squadre SQUADRE = Squadre.SQUADRE;

    /**
     * The table <code>TipologieCampo</code>.
     */
    public final Tipologiecampo TIPOLOGIECAMPO = Tipologiecampo.TIPOLOGIECAMPO;

    /**
     * The table <code>Transazioni</code>.
     */
    public final Transazioni TRANSAZIONI = Transazioni.TRANSAZIONI;

    /**
     * The table <code>Utenti</code>.
     */
    public final Utenti UTENTI = Utenti.UTENTI;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Centrisportivi.CENTRISPORTIVI,
            Dettaglioservizicentri.DETTAGLIOSERVIZICENTRI,
            Dettagliotipologiecentri.DETTAGLIOTIPOLOGIECENTRI,
            Disponibilita.DISPONIBILITA,
            Feedback.FEEDBACK,
            Gestori.GESTORI,
            Livelli.LIVELLI,
            Messaggigesorg.MESSAGGIGESORG,
            Messaggiorgfin.MESSAGGIORGFIN,
            Partite.PARTITE,
            Serviziaggiuntivi.SERVIZIAGGIUNTIVI,
            Squadre.SQUADRE,
            Tipologiecampo.TIPOLOGIECAMPO,
            Transazioni.TRANSAZIONI,
            Utenti.UTENTI
        );
    }
}
