/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer;


import sport_mate_inc.sport_mate_business_layer.tables.Centrisportivi;
import sport_mate_inc.sport_mate_business_layer.tables.Dettaglioservizicentri;
import sport_mate_inc.sport_mate_business_layer.tables.Dettagliotipologiecentri;
import sport_mate_inc.sport_mate_business_layer.tables.Disponibilita;
import sport_mate_inc.sport_mate_business_layer.tables.Feedback;
import sport_mate_inc.sport_mate_business_layer.tables.Gestori;
import sport_mate_inc.sport_mate_business_layer.tables.Livelli;
import sport_mate_inc.sport_mate_business_layer.tables.Messaggigesorg;
import sport_mate_inc.sport_mate_business_layer.tables.Messaggiorgfin;
import sport_mate_inc.sport_mate_business_layer.tables.Partite;
import sport_mate_inc.sport_mate_business_layer.tables.Serviziaggiuntivi;
import sport_mate_inc.sport_mate_business_layer.tables.Squadre;
import sport_mate_inc.sport_mate_business_layer.tables.Tipologiecampo;
import sport_mate_inc.sport_mate_business_layer.tables.Transazioni;
import sport_mate_inc.sport_mate_business_layer.tables.Utenti;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CentriSportivi</code>.
     */
    public static final Centrisportivi CENTRISPORTIVI = Centrisportivi.CENTRISPORTIVI;

    /**
     * The table <code>DettaglioServiziCentri</code>.
     */
    public static final Dettaglioservizicentri DETTAGLIOSERVIZICENTRI = Dettaglioservizicentri.DETTAGLIOSERVIZICENTRI;

    /**
     * The table <code>DettaglioTipologieCentri</code>.
     */
    public static final Dettagliotipologiecentri DETTAGLIOTIPOLOGIECENTRI = Dettagliotipologiecentri.DETTAGLIOTIPOLOGIECENTRI;

    /**
     * The table <code>Disponibilita</code>.
     */
    public static final Disponibilita DISPONIBILITA = Disponibilita.DISPONIBILITA;

    /**
     * The table <code>Feedback</code>.
     */
    public static final Feedback FEEDBACK = Feedback.FEEDBACK;

    /**
     * The table <code>Gestori</code>.
     */
    public static final Gestori GESTORI = Gestori.GESTORI;

    /**
     * The table <code>Livelli</code>.
     */
    public static final Livelli LIVELLI = Livelli.LIVELLI;

    /**
     * The table <code>MessaggiGesOrg</code>.
     */
    public static final Messaggigesorg MESSAGGIGESORG = Messaggigesorg.MESSAGGIGESORG;

    /**
     * The table <code>MessaggiOrgFin</code>.
     */
    public static final Messaggiorgfin MESSAGGIORGFIN = Messaggiorgfin.MESSAGGIORGFIN;

    /**
     * The table <code>Partite</code>.
     */
    public static final Partite PARTITE = Partite.PARTITE;

    /**
     * The table <code>ServiziAggiuntivi</code>.
     */
    public static final Serviziaggiuntivi SERVIZIAGGIUNTIVI = Serviziaggiuntivi.SERVIZIAGGIUNTIVI;

    /**
     * The table <code>Squadre</code>.
     */
    public static final Squadre SQUADRE = Squadre.SQUADRE;

    /**
     * The table <code>TipologieCampo</code>.
     */
    public static final Tipologiecampo TIPOLOGIECAMPO = Tipologiecampo.TIPOLOGIECAMPO;

    /**
     * The table <code>Transazioni</code>.
     */
    public static final Transazioni TRANSAZIONI = Transazioni.TRANSAZIONI;

    /**
     * The table <code>Utenti</code>.
     */
    public static final Utenti UTENTI = Utenti.UTENTI;
}
