/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.DettaglioservizicentriRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dettaglioservizicentri extends TableImpl<DettaglioservizicentriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DettaglioServiziCentri</code>
     */
    public static final Dettaglioservizicentri DETTAGLIOSERVIZICENTRI = new Dettaglioservizicentri();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DettaglioservizicentriRecord> getRecordType() {
        return DettaglioservizicentriRecord.class;
    }

    /**
     * The column <code>DettaglioServiziCentri.idServizio</code>.
     */
    public final TableField<DettaglioservizicentriRecord, Integer> IDSERVIZIO = createField(DSL.name("idServizio"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DettaglioServiziCentri.idCentro</code>.
     */
    public final TableField<DettaglioservizicentriRecord, Integer> IDCENTRO = createField(DSL.name("idCentro"), SQLDataType.INTEGER, this, "");

    private Dettaglioservizicentri(Name alias, Table<DettaglioservizicentriRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Dettaglioservizicentri(Name alias, Table<DettaglioservizicentriRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>DettaglioServiziCentri</code> table reference
     */
    public Dettaglioservizicentri(String alias) {
        this(DSL.name(alias), DETTAGLIOSERVIZICENTRI);
    }

    /**
     * Create an aliased <code>DettaglioServiziCentri</code> table reference
     */
    public Dettaglioservizicentri(Name alias) {
        this(alias, DETTAGLIOSERVIZICENTRI);
    }

    /**
     * Create a <code>DettaglioServiziCentri</code> table reference
     */
    public Dettaglioservizicentri() {
        this(DSL.name("DettaglioServiziCentri"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Dettaglioservizicentri as(String alias) {
        return new Dettaglioservizicentri(DSL.name(alias), this);
    }

    @Override
    public Dettaglioservizicentri as(Name alias) {
        return new Dettaglioservizicentri(alias, this);
    }

    @Override
    public Dettaglioservizicentri as(Table<?> alias) {
        return new Dettaglioservizicentri(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettaglioservizicentri rename(String name) {
        return new Dettaglioservizicentri(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettaglioservizicentri rename(Name name) {
        return new Dettaglioservizicentri(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettaglioservizicentri rename(Table<?> name) {
        return new Dettaglioservizicentri(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri where(Condition condition) {
        return new Dettaglioservizicentri(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettaglioservizicentri where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettaglioservizicentri where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettaglioservizicentri where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettaglioservizicentri where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettaglioservizicentri whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
