/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.DettagliotipologiecentriRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dettagliotipologiecentri extends TableImpl<DettagliotipologiecentriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DettaglioTipologieCentri</code>
     */
    public static final Dettagliotipologiecentri DETTAGLIOTIPOLOGIECENTRI = new Dettagliotipologiecentri();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DettagliotipologiecentriRecord> getRecordType() {
        return DettagliotipologiecentriRecord.class;
    }

    /**
     * The column <code>DettaglioTipologieCentri.idCentro</code>.
     */
    public final TableField<DettagliotipologiecentriRecord, Integer> IDCENTRO = createField(DSL.name("idCentro"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DettaglioTipologieCentri.idTipologia</code>.
     */
    public final TableField<DettagliotipologiecentriRecord, Integer> IDTIPOLOGIA = createField(DSL.name("idTipologia"), SQLDataType.INTEGER, this, "");

    private Dettagliotipologiecentri(Name alias, Table<DettagliotipologiecentriRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Dettagliotipologiecentri(Name alias, Table<DettagliotipologiecentriRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri(String alias) {
        this(DSL.name(alias), DETTAGLIOTIPOLOGIECENTRI);
    }

    /**
     * Create an aliased <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri(Name alias) {
        this(alias, DETTAGLIOTIPOLOGIECENTRI);
    }

    /**
     * Create a <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri() {
        this(DSL.name("DettaglioTipologieCentri"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Dettagliotipologiecentri as(String alias) {
        return new Dettagliotipologiecentri(DSL.name(alias), this);
    }

    @Override
    public Dettagliotipologiecentri as(Name alias) {
        return new Dettagliotipologiecentri(alias, this);
    }

    @Override
    public Dettagliotipologiecentri as(Table<?> alias) {
        return new Dettagliotipologiecentri(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(String name) {
        return new Dettagliotipologiecentri(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(Name name) {
        return new Dettagliotipologiecentri(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(Table<?> name) {
        return new Dettagliotipologiecentri(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri where(Condition condition) {
        return new Dettagliotipologiecentri(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettagliotipologiecentri where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettagliotipologiecentri where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettagliotipologiecentri where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dettagliotipologiecentri where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dettagliotipologiecentri whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
