/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.FeedbackRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Feedback extends TableImpl<FeedbackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Feedback</code>
     */
    public static final Feedback FEEDBACK = new Feedback();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedbackRecord> getRecordType() {
        return FeedbackRecord.class;
    }

    /**
     * The column <code>Feedback.idFeedback</code>.
     */
    public final TableField<FeedbackRecord, Integer> IDFEEDBACK = createField(DSL.name("idFeedback"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Feedback.oggetto</code>.
     */
    public final TableField<FeedbackRecord, String> OGGETTO = createField(DSL.name("oggetto"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Feedback.testo</code>.
     */
    public final TableField<FeedbackRecord, String> TESTO = createField(DSL.name("testo"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Feedback.numLike</code>.
     */
    public final TableField<FeedbackRecord, Integer> NUMLIKE = createField(DSL.name("numLike"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Feedback.idUtente</code>.
     */
    public final TableField<FeedbackRecord, Integer> IDUTENTE = createField(DSL.name("idUtente"), SQLDataType.INTEGER.nullable(false), this, "");

    private Feedback(Name alias, Table<FeedbackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Feedback(Name alias, Table<FeedbackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Feedback</code> table reference
     */
    public Feedback(String alias) {
        this(DSL.name(alias), FEEDBACK);
    }

    /**
     * Create an aliased <code>Feedback</code> table reference
     */
    public Feedback(Name alias) {
        this(alias, FEEDBACK);
    }

    /**
     * Create a <code>Feedback</code> table reference
     */
    public Feedback() {
        this(DSL.name("Feedback"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeedbackRecord, Integer> getIdentity() {
        return (Identity<FeedbackRecord, Integer>) super.getIdentity();
    }

    @Override
    public Feedback as(String alias) {
        return new Feedback(DSL.name(alias), this);
    }

    @Override
    public Feedback as(Name alias) {
        return new Feedback(alias, this);
    }

    @Override
    public Feedback as(Table<?> alias) {
        return new Feedback(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Feedback rename(String name) {
        return new Feedback(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Feedback rename(Name name) {
        return new Feedback(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Feedback rename(Table<?> name) {
        return new Feedback(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback where(Condition condition) {
        return new Feedback(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Feedback where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Feedback where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Feedback where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Feedback where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Feedback whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
