/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.GestoriRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Gestori extends TableImpl<GestoriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Gestori</code>
     */
    public static final Gestori GESTORI = new Gestori();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GestoriRecord> getRecordType() {
        return GestoriRecord.class;
    }

    /**
     * The column <code>Gestori.idGestore</code>.
     */
    public final TableField<GestoriRecord, Integer> IDGESTORE = createField(DSL.name("idGestore"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Gestori.nome</code>.
     */
    public final TableField<GestoriRecord, String> NOME = createField(DSL.name("nome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gestori.cognome</code>.
     */
    public final TableField<GestoriRecord, String> COGNOME = createField(DSL.name("cognome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gestori.dataNascita</code>.
     */
    public final TableField<GestoriRecord, String> DATANASCITA = createField(DSL.name("dataNascita"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gestori.mail</code>.
     */
    public final TableField<GestoriRecord, String> MAIL = createField(DSL.name("mail"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gestori.telefono</code>.
     */
    public final TableField<GestoriRecord, String> TELEFONO = createField(DSL.name("telefono"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gestori.password</code>.
     */
    public final TableField<GestoriRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.CLOB.nullable(false), this, "");

    private Gestori(Name alias, Table<GestoriRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Gestori(Name alias, Table<GestoriRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Gestori</code> table reference
     */
    public Gestori(String alias) {
        this(DSL.name(alias), GESTORI);
    }

    /**
     * Create an aliased <code>Gestori</code> table reference
     */
    public Gestori(Name alias) {
        this(alias, GESTORI);
    }

    /**
     * Create a <code>Gestori</code> table reference
     */
    public Gestori() {
        this(DSL.name("Gestori"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Gestori as(String alias) {
        return new Gestori(DSL.name(alias), this);
    }

    @Override
    public Gestori as(Name alias) {
        return new Gestori(alias, this);
    }

    @Override
    public Gestori as(Table<?> alias) {
        return new Gestori(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gestori rename(String name) {
        return new Gestori(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gestori rename(Name name) {
        return new Gestori(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gestori rename(Table<?> name) {
        return new Gestori(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori where(Condition condition) {
        return new Gestori(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gestori where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gestori where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gestori where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Gestori where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Gestori whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
