/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.LivelliRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Livelli extends TableImpl<LivelliRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Livelli</code>
     */
    public static final Livelli LIVELLI = new Livelli();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LivelliRecord> getRecordType() {
        return LivelliRecord.class;
    }

    /**
     * The column <code>Livelli.idLivello</code>.
     */
    public final TableField<LivelliRecord, Integer> IDLIVELLO = createField(DSL.name("idLivello"), SQLDataType.INTEGER.identity(true).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>Livelli.nomeLivello</code>.
     */
    public final TableField<LivelliRecord, String> NOMELIVELLO = createField(DSL.name("nomeLivello"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'Principiante'"), SQLDataType.CLOB)), this, "");

    private Livelli(Name alias, Table<LivelliRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Livelli(Name alias, Table<LivelliRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Livelli</code> table reference
     */
    public Livelli(String alias) {
        this(DSL.name(alias), LIVELLI);
    }

    /**
     * Create an aliased <code>Livelli</code> table reference
     */
    public Livelli(Name alias) {
        this(alias, LIVELLI);
    }

    /**
     * Create a <code>Livelli</code> table reference
     */
    public Livelli() {
        this(DSL.name("Livelli"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<LivelliRecord, Integer> getIdentity() {
        return (Identity<LivelliRecord, Integer>) super.getIdentity();
    }

    @Override
    public Livelli as(String alias) {
        return new Livelli(DSL.name(alias), this);
    }

    @Override
    public Livelli as(Name alias) {
        return new Livelli(alias, this);
    }

    @Override
    public Livelli as(Table<?> alias) {
        return new Livelli(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Livelli rename(String name) {
        return new Livelli(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Livelli rename(Name name) {
        return new Livelli(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Livelli rename(Table<?> name) {
        return new Livelli(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli where(Condition condition) {
        return new Livelli(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Livelli where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Livelli where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Livelli where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Livelli where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Livelli whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
