/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.MessaggigesorgRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messaggigesorg extends TableImpl<MessaggigesorgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MessaggiGesOrg</code>
     */
    public static final Messaggigesorg MESSAGGIGESORG = new Messaggigesorg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessaggigesorgRecord> getRecordType() {
        return MessaggigesorgRecord.class;
    }

    /**
     * The column <code>MessaggiGesOrg.idMessaggio</code>.
     */
    public final TableField<MessaggigesorgRecord, Integer> IDMESSAGGIO = createField(DSL.name("idMessaggio"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>MessaggiGesOrg.stato</code>.
     */
    public final TableField<MessaggigesorgRecord, Integer> STATO = createField(DSL.name("stato"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MessaggiGesOrg.testo</code>.
     */
    public final TableField<MessaggigesorgRecord, String> TESTO = createField(DSL.name("testo"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>MessaggiGesOrg.dataOra</code>.
     */
    public final TableField<MessaggigesorgRecord, String> DATAORA = createField(DSL.name("dataOra"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>MessaggiGesOrg.idGestore</code>.
     */
    public final TableField<MessaggigesorgRecord, Integer> IDGESTORE = createField(DSL.name("idGestore"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MessaggiGesOrg.idOrganizzatore</code>.
     */
    public final TableField<MessaggigesorgRecord, Integer> IDORGANIZZATORE = createField(DSL.name("idOrganizzatore"), SQLDataType.INTEGER.nullable(false), this, "");

    private Messaggigesorg(Name alias, Table<MessaggigesorgRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messaggigesorg(Name alias, Table<MessaggigesorgRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MessaggiGesOrg</code> table reference
     */
    public Messaggigesorg(String alias) {
        this(DSL.name(alias), MESSAGGIGESORG);
    }

    /**
     * Create an aliased <code>MessaggiGesOrg</code> table reference
     */
    public Messaggigesorg(Name alias) {
        this(alias, MESSAGGIGESORG);
    }

    /**
     * Create a <code>MessaggiGesOrg</code> table reference
     */
    public Messaggigesorg() {
        this(DSL.name("MessaggiGesOrg"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<MessaggigesorgRecord, Integer> getIdentity() {
        return (Identity<MessaggigesorgRecord, Integer>) super.getIdentity();
    }

    @Override
    public Messaggigesorg as(String alias) {
        return new Messaggigesorg(DSL.name(alias), this);
    }

    @Override
    public Messaggigesorg as(Name alias) {
        return new Messaggigesorg(alias, this);
    }

    @Override
    public Messaggigesorg as(Table<?> alias) {
        return new Messaggigesorg(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggigesorg rename(String name) {
        return new Messaggigesorg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggigesorg rename(Name name) {
        return new Messaggigesorg(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggigesorg rename(Table<?> name) {
        return new Messaggigesorg(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg where(Condition condition) {
        return new Messaggigesorg(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messaggigesorg where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messaggigesorg where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messaggigesorg where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messaggigesorg where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messaggigesorg whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
