/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.PartiteRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Partite extends TableImpl<PartiteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Partite</code>
     */
    public static final Partite PARTITE = new Partite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartiteRecord> getRecordType() {
        return PartiteRecord.class;
    }

    /**
     * The column <code>Partite.idPartita</code>.
     */
    public final TableField<PartiteRecord, Integer> IDPARTITA = createField(DSL.name("idPartita"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Partite.postiTotali</code>.
     */
    public final TableField<PartiteRecord, Integer> POSTITOTALI = createField(DSL.name("postiTotali"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Partite.pubblica</code>.
     */
    public final TableField<PartiteRecord, Integer> PUBBLICA = createField(DSL.name("pubblica"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Partite.sato</code>.
     */
    public final TableField<PartiteRecord, Integer> SATO = createField(DSL.name("sato"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Partite.modPagamento</code>.
     */
    public final TableField<PartiteRecord, String> MODPAGAMENTO = createField(DSL.name("modPagamento"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Partite.idOrganizzatore</code>.
     */
    public final TableField<PartiteRecord, Integer> IDORGANIZZATORE = createField(DSL.name("idOrganizzatore"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Partite.idDisponibilità</code>.
     */
    public final TableField<PartiteRecord, Integer> IDDISPONIBILITÀ = createField(DSL.name("idDisponibilità"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Partite.goalSquadraCasa</code>.
     */
    public final TableField<PartiteRecord, Integer> GOALSQUADRACASA = createField(DSL.name("goalSquadraCasa"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Partite.goalSquadraTrasferta</code>.
     */
    public final TableField<PartiteRecord, Integer> GOALSQUADRATRASFERTA = createField(DSL.name("goalSquadraTrasferta"), SQLDataType.INTEGER, this, "");

    private Partite(Name alias, Table<PartiteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Partite(Name alias, Table<PartiteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Partite</code> table reference
     */
    public Partite(String alias) {
        this(DSL.name(alias), PARTITE);
    }

    /**
     * Create an aliased <code>Partite</code> table reference
     */
    public Partite(Name alias) {
        this(alias, PARTITE);
    }

    /**
     * Create a <code>Partite</code> table reference
     */
    public Partite() {
        this(DSL.name("Partite"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<PartiteRecord, Integer> getIdentity() {
        return (Identity<PartiteRecord, Integer>) super.getIdentity();
    }

    @Override
    public Partite as(String alias) {
        return new Partite(DSL.name(alias), this);
    }

    @Override
    public Partite as(Name alias) {
        return new Partite(alias, this);
    }

    @Override
    public Partite as(Table<?> alias) {
        return new Partite(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Partite rename(String name) {
        return new Partite(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partite rename(Name name) {
        return new Partite(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Partite rename(Table<?> name) {
        return new Partite(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite where(Condition condition) {
        return new Partite(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partite where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partite where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partite where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Partite where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Partite whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
