/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.ServiziaggiuntiviRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Serviziaggiuntivi extends TableImpl<ServiziaggiuntiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ServiziAggiuntivi</code>
     */
    public static final Serviziaggiuntivi SERVIZIAGGIUNTIVI = new Serviziaggiuntivi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiziaggiuntiviRecord> getRecordType() {
        return ServiziaggiuntiviRecord.class;
    }

    /**
     * The column <code>ServiziAggiuntivi.idServizio</code>.
     */
    public final TableField<ServiziaggiuntiviRecord, Integer> IDSERVIZIO = createField(DSL.name("idServizio"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>ServiziAggiuntivi.nomeServizio</code>.
     */
    public final TableField<ServiziaggiuntiviRecord, String> NOMESERVIZIO = createField(DSL.name("nomeServizio"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ServiziAggiuntivi.descrizione</code>.
     */
    public final TableField<ServiziaggiuntiviRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.CLOB.nullable(false), this, "");

    private Serviziaggiuntivi(Name alias, Table<ServiziaggiuntiviRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Serviziaggiuntivi(Name alias, Table<ServiziaggiuntiviRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ServiziAggiuntivi</code> table reference
     */
    public Serviziaggiuntivi(String alias) {
        this(DSL.name(alias), SERVIZIAGGIUNTIVI);
    }

    /**
     * Create an aliased <code>ServiziAggiuntivi</code> table reference
     */
    public Serviziaggiuntivi(Name alias) {
        this(alias, SERVIZIAGGIUNTIVI);
    }

    /**
     * Create a <code>ServiziAggiuntivi</code> table reference
     */
    public Serviziaggiuntivi() {
        this(DSL.name("ServiziAggiuntivi"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ServiziaggiuntiviRecord, Integer> getIdentity() {
        return (Identity<ServiziaggiuntiviRecord, Integer>) super.getIdentity();
    }

    @Override
    public Serviziaggiuntivi as(String alias) {
        return new Serviziaggiuntivi(DSL.name(alias), this);
    }

    @Override
    public Serviziaggiuntivi as(Name alias) {
        return new Serviziaggiuntivi(alias, this);
    }

    @Override
    public Serviziaggiuntivi as(Table<?> alias) {
        return new Serviziaggiuntivi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Serviziaggiuntivi rename(String name) {
        return new Serviziaggiuntivi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Serviziaggiuntivi rename(Name name) {
        return new Serviziaggiuntivi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Serviziaggiuntivi rename(Table<?> name) {
        return new Serviziaggiuntivi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi where(Condition condition) {
        return new Serviziaggiuntivi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Serviziaggiuntivi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Serviziaggiuntivi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Serviziaggiuntivi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Serviziaggiuntivi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Serviziaggiuntivi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
