/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.SquadreRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Squadre extends TableImpl<SquadreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Squadre</code>
     */
    public static final Squadre SQUADRE = new Squadre();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SquadreRecord> getRecordType() {
        return SquadreRecord.class;
    }

    /**
     * The column <code>Squadre.idSquadra</code>.
     */
    public final TableField<SquadreRecord, Integer> IDSQUADRA = createField(DSL.name("idSquadra"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Squadre.nomeSquadra</code>.
     */
    public final TableField<SquadreRecord, String> NOMESQUADRA = createField(DSL.name("nomeSquadra"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Squadre.coloreMaglia</code>.
     */
    public final TableField<SquadreRecord, String> COLOREMAGLIA = createField(DSL.name("coloreMaglia"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Squadre.inCasa</code>.
     */
    public final TableField<SquadreRecord, Integer> INCASA = createField(DSL.name("inCasa"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Squadre.idPartita</code>.
     */
    public final TableField<SquadreRecord, Integer> IDPARTITA = createField(DSL.name("idPartita"), SQLDataType.INTEGER.nullable(false), this, "");

    private Squadre(Name alias, Table<SquadreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Squadre(Name alias, Table<SquadreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Squadre</code> table reference
     */
    public Squadre(String alias) {
        this(DSL.name(alias), SQUADRE);
    }

    /**
     * Create an aliased <code>Squadre</code> table reference
     */
    public Squadre(Name alias) {
        this(alias, SQUADRE);
    }

    /**
     * Create a <code>Squadre</code> table reference
     */
    public Squadre() {
        this(DSL.name("Squadre"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<SquadreRecord, Integer> getIdentity() {
        return (Identity<SquadreRecord, Integer>) super.getIdentity();
    }

    @Override
    public Squadre as(String alias) {
        return new Squadre(DSL.name(alias), this);
    }

    @Override
    public Squadre as(Name alias) {
        return new Squadre(alias, this);
    }

    @Override
    public Squadre as(Table<?> alias) {
        return new Squadre(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Squadre rename(String name) {
        return new Squadre(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Squadre rename(Name name) {
        return new Squadre(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Squadre rename(Table<?> name) {
        return new Squadre(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre where(Condition condition) {
        return new Squadre(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Squadre where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Squadre where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Squadre where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Squadre where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Squadre whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
