/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.TipologiecampoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tipologiecampo extends TableImpl<TipologiecampoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TipologieCampo</code>
     */
    public static final Tipologiecampo TIPOLOGIECAMPO = new Tipologiecampo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TipologiecampoRecord> getRecordType() {
        return TipologiecampoRecord.class;
    }

    /**
     * The column <code>TipologieCampo.idTipologia</code>.
     */
    public final TableField<TipologiecampoRecord, Integer> IDTIPOLOGIA = createField(DSL.name("idTipologia"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>TipologieCampo.nomeTipologia</code>.
     */
    public final TableField<TipologiecampoRecord, String> NOMETIPOLOGIA = createField(DSL.name("nomeTipologia"), SQLDataType.CLOB.nullable(false), this, "");

    private Tipologiecampo(Name alias, Table<TipologiecampoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tipologiecampo(Name alias, Table<TipologiecampoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo(String alias) {
        this(DSL.name(alias), TIPOLOGIECAMPO);
    }

    /**
     * Create an aliased <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo(Name alias) {
        this(alias, TIPOLOGIECAMPO);
    }

    /**
     * Create a <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo() {
        this(DSL.name("TipologieCampo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<TipologiecampoRecord, Integer> getIdentity() {
        return (Identity<TipologiecampoRecord, Integer>) super.getIdentity();
    }

    @Override
    public Tipologiecampo as(String alias) {
        return new Tipologiecampo(DSL.name(alias), this);
    }

    @Override
    public Tipologiecampo as(Name alias) {
        return new Tipologiecampo(alias, this);
    }

    @Override
    public Tipologiecampo as(Table<?> alias) {
        return new Tipologiecampo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(String name) {
        return new Tipologiecampo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(Name name) {
        return new Tipologiecampo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(Table<?> name) {
        return new Tipologiecampo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo where(Condition condition) {
        return new Tipologiecampo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tipologiecampo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tipologiecampo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tipologiecampo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tipologiecampo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tipologiecampo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
