/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.TransazioniRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Transazioni extends TableImpl<TransazioniRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Transazioni</code>
     */
    public static final Transazioni TRANSAZIONI = new Transazioni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransazioniRecord> getRecordType() {
        return TransazioniRecord.class;
    }

    /**
     * The column <code>Transazioni.idTransazione</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDTRANSAZIONE = createField(DSL.name("idTransazione"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Transazioni.importo</code>.
     */
    public final TableField<TransazioniRecord, BigDecimal> IMPORTO = createField(DSL.name("importo"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>Transazioni.data</code>.
     */
    public final TableField<TransazioniRecord, String> DATA = createField(DSL.name("data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Transazioni.idPartita</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDPARTITA = createField(DSL.name("idPartita"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Transazioni.idUtente</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDUTENTE = createField(DSL.name("idUtente"), SQLDataType.INTEGER.nullable(false), this, "");

    private Transazioni(Name alias, Table<TransazioniRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Transazioni(Name alias, Table<TransazioniRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Transazioni</code> table reference
     */
    public Transazioni(String alias) {
        this(DSL.name(alias), TRANSAZIONI);
    }

    /**
     * Create an aliased <code>Transazioni</code> table reference
     */
    public Transazioni(Name alias) {
        this(alias, TRANSAZIONI);
    }

    /**
     * Create a <code>Transazioni</code> table reference
     */
    public Transazioni() {
        this(DSL.name("Transazioni"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<TransazioniRecord, Integer> getIdentity() {
        return (Identity<TransazioniRecord, Integer>) super.getIdentity();
    }

    @Override
    public Transazioni as(String alias) {
        return new Transazioni(DSL.name(alias), this);
    }

    @Override
    public Transazioni as(Name alias) {
        return new Transazioni(alias, this);
    }

    @Override
    public Transazioni as(Table<?> alias) {
        return new Transazioni(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(String name) {
        return new Transazioni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(Name name) {
        return new Transazioni(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(Table<?> name) {
        return new Transazioni(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni where(Condition condition) {
        return new Transazioni(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transazioni where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transazioni where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transazioni where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transazioni where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transazioni whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
