/*
 * This file is generated by jOOQ.
 */
package sport_mate_inc.sport_mate_business_layer.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import sport_mate_inc.sport_mate_business_layer.DefaultSchema;
import sport_mate_inc.sport_mate_business_layer.tables.records.UtentiRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Utenti extends TableImpl<UtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Utenti</code>
     */
    public static final Utenti UTENTI = new Utenti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtentiRecord> getRecordType() {
        return UtentiRecord.class;
    }

    /**
     * The column <code>Utenti.idUtente</code>.
     */
    public final TableField<UtentiRecord, Integer> IDUTENTE = createField(DSL.name("idUtente"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Utenti.nome</code>.
     */
    public final TableField<UtentiRecord, String> NOME = createField(DSL.name("nome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.cognome</code>.
     */
    public final TableField<UtentiRecord, String> COGNOME = createField(DSL.name("cognome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.dataNascita</code>.
     */
    public final TableField<UtentiRecord, String> DATANASCITA = createField(DSL.name("dataNascita"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.mail</code>.
     */
    public final TableField<UtentiRecord, String> MAIL = createField(DSL.name("mail"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.telefono</code>.
     */
    public final TableField<UtentiRecord, String> TELEFONO = createField(DSL.name("telefono"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Utenti.password</code>.
     */
    public final TableField<UtentiRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.credito</code>.
     */
    public final TableField<UtentiRecord, BigDecimal> CREDITO = createField(DSL.name("credito"), SQLDataType.NUMERIC.nullable(false).defaultValue(DSL.field(DSL.raw("10"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>Utenti.livello</code>.
     */
    public final TableField<UtentiRecord, Integer> LIVELLO = createField(DSL.name("livello"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>Utenti.pathImg</code>.
     */
    public final TableField<UtentiRecord, String> PATHIMG = createField(DSL.name("pathImg"), SQLDataType.CLOB, this, "");

    private Utenti(Name alias, Table<UtentiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Utenti(Name alias, Table<UtentiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Utenti</code> table reference
     */
    public Utenti(String alias) {
        this(DSL.name(alias), UTENTI);
    }

    /**
     * Create an aliased <code>Utenti</code> table reference
     */
    public Utenti(Name alias) {
        this(alias, UTENTI);
    }

    /**
     * Create a <code>Utenti</code> table reference
     */
    public Utenti() {
        this(DSL.name("Utenti"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<UtentiRecord, Integer> getIdentity() {
        return (Identity<UtentiRecord, Integer>) super.getIdentity();
    }

    @Override
    public Utenti as(String alias) {
        return new Utenti(DSL.name(alias), this);
    }

    @Override
    public Utenti as(Name alias) {
        return new Utenti(alias, this);
    }

    @Override
    public Utenti as(Table<?> alias) {
        return new Utenti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(String name) {
        return new Utenti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Name name) {
        return new Utenti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Table<?> name) {
        return new Utenti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Condition condition) {
        return new Utenti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
