/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables.records;


import SportMateInc.SportMateBusinessLayer.tables.Messaggigesorg;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessaggigesorgRecord extends TableRecordImpl<MessaggigesorgRecord> implements Record6<Integer, Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MessaggiGesOrg.idMessaggio</code>.
     */
    public void setIdmessaggio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idMessaggio</code>.
     */
    public Integer getIdmessaggio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MessaggiGesOrg.stato</code>.
     */
    public void setStato(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.stato</code>.
     */
    public Integer getStato() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MessaggiGesOrg.testo</code>.
     */
    public void setTesto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.testo</code>.
     */
    public String getTesto() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MessaggiGesOrg.dataOra</code>.
     */
    public void setDataora(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.dataOra</code>.
     */
    public String getDataora() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MessaggiGesOrg.idGestore</code>.
     */
    public void setIdgestore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idGestore</code>.
     */
    public Integer getIdgestore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MessaggiGesOrg.idOrganizzatore</code>.
     */
    public void setIdorganizzatore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MessaggiGesOrg.idOrganizzatore</code>.
     */
    public Integer getIdorganizzatore() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Messaggigesorg.MESSAGGIGESORG.IDMESSAGGIO;
    }

    @Override
    public Field<Integer> field2() {
        return Messaggigesorg.MESSAGGIGESORG.STATO;
    }

    @Override
    public Field<String> field3() {
        return Messaggigesorg.MESSAGGIGESORG.TESTO;
    }

    @Override
    public Field<String> field4() {
        return Messaggigesorg.MESSAGGIGESORG.DATAORA;
    }

    @Override
    public Field<Integer> field5() {
        return Messaggigesorg.MESSAGGIGESORG.IDGESTORE;
    }

    @Override
    public Field<Integer> field6() {
        return Messaggigesorg.MESSAGGIGESORG.IDORGANIZZATORE;
    }

    @Override
    public Integer component1() {
        return getIdmessaggio();
    }

    @Override
    public Integer component2() {
        return getStato();
    }

    @Override
    public String component3() {
        return getTesto();
    }

    @Override
    public String component4() {
        return getDataora();
    }

    @Override
    public Integer component5() {
        return getIdgestore();
    }

    @Override
    public Integer component6() {
        return getIdorganizzatore();
    }

    @Override
    public Integer value1() {
        return getIdmessaggio();
    }

    @Override
    public Integer value2() {
        return getStato();
    }

    @Override
    public String value3() {
        return getTesto();
    }

    @Override
    public String value4() {
        return getDataora();
    }

    @Override
    public Integer value5() {
        return getIdgestore();
    }

    @Override
    public Integer value6() {
        return getIdorganizzatore();
    }

    @Override
    public MessaggigesorgRecord value1(Integer value) {
        setIdmessaggio(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord value2(Integer value) {
        setStato(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord value3(String value) {
        setTesto(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord value4(String value) {
        setDataora(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord value5(Integer value) {
        setIdgestore(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord value6(Integer value) {
        setIdorganizzatore(value);
        return this;
    }

    @Override
    public MessaggigesorgRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessaggigesorgRecord
     */
    public MessaggigesorgRecord() {
        super(Messaggigesorg.MESSAGGIGESORG);
    }

    /**
     * Create a detached, initialised MessaggigesorgRecord
     */
    public MessaggigesorgRecord(Integer idmessaggio, Integer stato, String testo, String dataora, Integer idgestore, Integer idorganizzatore) {
        super(Messaggigesorg.MESSAGGIGESORG);

        setIdmessaggio(idmessaggio);
        setStato(stato);
        setTesto(testo);
        setDataora(dataora);
        setIdgestore(idgestore);
        setIdorganizzatore(idorganizzatore);
        resetChangedOnNotNull();
    }
}
