/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables.records;


import SportMateInc.SportMateBusinessLayer.tables.Tipologiecampo;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TipologiecampoRecord extends TableRecordImpl<TipologiecampoRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TipologieCampo.idTipologia</code>.
     */
    public void setIdtipologia(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TipologieCampo.idTipologia</code>.
     */
    public Integer getIdtipologia() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TipologieCampo.nomeTipologia</code>.
     */
    public void setNometipologia(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TipologieCampo.nomeTipologia</code>.
     */
    public String getNometipologia() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tipologiecampo.TIPOLOGIECAMPO.IDTIPOLOGIA;
    }

    @Override
    public Field<String> field2() {
        return Tipologiecampo.TIPOLOGIECAMPO.NOMETIPOLOGIA;
    }

    @Override
    public Integer component1() {
        return getIdtipologia();
    }

    @Override
    public String component2() {
        return getNometipologia();
    }

    @Override
    public Integer value1() {
        return getIdtipologia();
    }

    @Override
    public String value2() {
        return getNometipologia();
    }

    @Override
    public TipologiecampoRecord value1(Integer value) {
        setIdtipologia(value);
        return this;
    }

    @Override
    public TipologiecampoRecord value2(String value) {
        setNometipologia(value);
        return this;
    }

    @Override
    public TipologiecampoRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TipologiecampoRecord
     */
    public TipologiecampoRecord() {
        super(Tipologiecampo.TIPOLOGIECAMPO);
    }

    /**
     * Create a detached, initialised TipologiecampoRecord
     */
    public TipologiecampoRecord(Integer idtipologia, String nometipologia) {
        super(Tipologiecampo.TIPOLOGIECAMPO);

        setIdtipologia(idtipologia);
        setNometipologia(nometipologia);
        resetChangedOnNotNull();
    }
}
