/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables.records;


import SportMateInc.SportMateBusinessLayer.tables.Transazioni;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransazioniRecord extends TableRecordImpl<TransazioniRecord> implements Record5<Integer, BigDecimal, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Transazioni.idTransazione</code>.
     */
    public void setIdtransazione(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Transazioni.idTransazione</code>.
     */
    public Integer getIdtransazione() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Transazioni.importo</code>.
     */
    public void setImporto(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>Transazioni.importo</code>.
     */
    public BigDecimal getImporto() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>Transazioni.data</code>.
     */
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Transazioni.data</code>.
     */
    public String getData() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Transazioni.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Transazioni.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Transazioni.idUtente</code>.
     */
    public void setIdutente(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Transazioni.idUtente</code>.
     */
    public Integer getIdutente() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, BigDecimal, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, BigDecimal, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Transazioni.TRANSAZIONI.IDTRANSAZIONE;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Transazioni.TRANSAZIONI.IMPORTO;
    }

    @Override
    public Field<String> field3() {
        return Transazioni.TRANSAZIONI.DATA;
    }

    @Override
    public Field<Integer> field4() {
        return Transazioni.TRANSAZIONI.IDPARTITA;
    }

    @Override
    public Field<Integer> field5() {
        return Transazioni.TRANSAZIONI.IDUTENTE;
    }

    @Override
    public Integer component1() {
        return getIdtransazione();
    }

    @Override
    public BigDecimal component2() {
        return getImporto();
    }

    @Override
    public String component3() {
        return getData();
    }

    @Override
    public Integer component4() {
        return getIdpartita();
    }

    @Override
    public Integer component5() {
        return getIdutente();
    }

    @Override
    public Integer value1() {
        return getIdtransazione();
    }

    @Override
    public BigDecimal value2() {
        return getImporto();
    }

    @Override
    public String value3() {
        return getData();
    }

    @Override
    public Integer value4() {
        return getIdpartita();
    }

    @Override
    public Integer value5() {
        return getIdutente();
    }

    @Override
    public TransazioniRecord value1(Integer value) {
        setIdtransazione(value);
        return this;
    }

    @Override
    public TransazioniRecord value2(BigDecimal value) {
        setImporto(value);
        return this;
    }

    @Override
    public TransazioniRecord value3(String value) {
        setData(value);
        return this;
    }

    @Override
    public TransazioniRecord value4(Integer value) {
        setIdpartita(value);
        return this;
    }

    @Override
    public TransazioniRecord value5(Integer value) {
        setIdutente(value);
        return this;
    }

    @Override
    public TransazioniRecord values(Integer value1, BigDecimal value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransazioniRecord
     */
    public TransazioniRecord() {
        super(Transazioni.TRANSAZIONI);
    }

    /**
     * Create a detached, initialised TransazioniRecord
     */
    public TransazioniRecord(Integer idtransazione, BigDecimal importo, String data, Integer idpartita, Integer idutente) {
        super(Transazioni.TRANSAZIONI);

        setIdtransazione(idtransazione);
        setImporto(importo);
        setData(data);
        setIdpartita(idpartita);
        setIdutente(idutente);
        resetChangedOnNotNull();
    }
}
