/*
 * This file is generated by jOOQ.
 */
package sportmateinc.sportmatebusinesslayergenerated.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;

import sportmateinc.sportmatebusinesslayergenerated.tables.Centrisportivi;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CentrisportiviRecord extends TableRecordImpl<CentrisportiviRecord> implements Record9<Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CentriSportivi.idCentro</code>.
     */
    public void setIdcentro(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CentriSportivi.idCentro</code>.
     */
    public Integer getIdcentro() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CentriSportivi.nomeCommerciale</code>.
     */
    public void setNomecommerciale(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CentriSportivi.nomeCommerciale</code>.
     */
    public String getNomecommerciale() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CentriSportivi.indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CentriSportivi.indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CentriSportivi.latitudine</code>.
     */
    public void setLatitudine(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>CentriSportivi.latitudine</code>.
     */
    public BigDecimal getLatitudine() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>CentriSportivi.longitudine</code>.
     */
    public void setLongitudine(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>CentriSportivi.longitudine</code>.
     */
    public BigDecimal getLongitudine() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>CentriSportivi.credito</code>.
     */
    public void setCredito(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>CentriSportivi.credito</code>.
     */
    public BigDecimal getCredito() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>CentriSportivi.orarioApertura</code>.
     */
    public void setOrarioapertura(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CentriSportivi.orarioApertura</code>.
     */
    public String getOrarioapertura() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CentriSportivi.orarioChiusura</code>.
     */
    public void setOrariochiusura(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CentriSportivi.orarioChiusura</code>.
     */
    public String getOrariochiusura() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CentriSportivi.idGestore</code>.
     */
    public void setIdgestore(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>CentriSportivi.idGestore</code>.
     */
    public Integer getIdgestore() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, BigDecimal, BigDecimal, BigDecimal, String, String, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Centrisportivi.CENTRISPORTIVI.IDCENTRO;
    }

    @Override
    public Field<String> field2() {
        return Centrisportivi.CENTRISPORTIVI.NOMECOMMERCIALE;
    }

    @Override
    public Field<String> field3() {
        return Centrisportivi.CENTRISPORTIVI.INDIRIZZO;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Centrisportivi.CENTRISPORTIVI.LATITUDINE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Centrisportivi.CENTRISPORTIVI.LONGITUDINE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Centrisportivi.CENTRISPORTIVI.CREDITO;
    }

    @Override
    public Field<String> field7() {
        return Centrisportivi.CENTRISPORTIVI.ORARIOAPERTURA;
    }

    @Override
    public Field<String> field8() {
        return Centrisportivi.CENTRISPORTIVI.ORARIOCHIUSURA;
    }

    @Override
    public Field<Integer> field9() {
        return Centrisportivi.CENTRISPORTIVI.IDGESTORE;
    }

    @Override
    public Integer component1() {
        return getIdcentro();
    }

    @Override
    public String component2() {
        return getNomecommerciale();
    }

    @Override
    public String component3() {
        return getIndirizzo();
    }

    @Override
    public BigDecimal component4() {
        return getLatitudine();
    }

    @Override
    public BigDecimal component5() {
        return getLongitudine();
    }

    @Override
    public BigDecimal component6() {
        return getCredito();
    }

    @Override
    public String component7() {
        return getOrarioapertura();
    }

    @Override
    public String component8() {
        return getOrariochiusura();
    }

    @Override
    public Integer component9() {
        return getIdgestore();
    }

    @Override
    public Integer value1() {
        return getIdcentro();
    }

    @Override
    public String value2() {
        return getNomecommerciale();
    }

    @Override
    public String value3() {
        return getIndirizzo();
    }

    @Override
    public BigDecimal value4() {
        return getLatitudine();
    }

    @Override
    public BigDecimal value5() {
        return getLongitudine();
    }

    @Override
    public BigDecimal value6() {
        return getCredito();
    }

    @Override
    public String value7() {
        return getOrarioapertura();
    }

    @Override
    public String value8() {
        return getOrariochiusura();
    }

    @Override
    public Integer value9() {
        return getIdgestore();
    }

    @Override
    public CentrisportiviRecord value1(Integer value) {
        setIdcentro(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value2(String value) {
        setNomecommerciale(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value3(String value) {
        setIndirizzo(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value4(BigDecimal value) {
        setLatitudine(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value5(BigDecimal value) {
        setLongitudine(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value6(BigDecimal value) {
        setCredito(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value7(String value) {
        setOrarioapertura(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value8(String value) {
        setOrariochiusura(value);
        return this;
    }

    @Override
    public CentrisportiviRecord value9(Integer value) {
        setIdgestore(value);
        return this;
    }

    @Override
    public CentrisportiviRecord values(Integer value1, String value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, String value7, String value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CentrisportiviRecord
     */
    public CentrisportiviRecord() {
        super(Centrisportivi.CENTRISPORTIVI);
    }

    /**
     * Create a detached, initialised CentrisportiviRecord
     */
    public CentrisportiviRecord(Integer idcentro, String nomecommerciale, String indirizzo, BigDecimal latitudine, BigDecimal longitudine, BigDecimal credito, String orarioapertura, String orariochiusura, Integer idgestore) {
        super(Centrisportivi.CENTRISPORTIVI);

        setIdcentro(idcentro);
        setNomecommerciale(nomecommerciale);
        setIndirizzo(indirizzo);
        setLatitudine(latitudine);
        setLongitudine(longitudine);
        setCredito(credito);
        setOrarioapertura(orarioapertura);
        setOrariochiusura(orariochiusura);
        setIdgestore(idgestore);
        resetChangedOnNotNull();
    }
}
