/*
 * This file is generated by jOOQ.
 */
package sportmateinc.sportmatebusinesslayergenerated.tables.records;


import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;

import sportmateinc.sportmatebusinesslayergenerated.tables.Partite;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PartiteRecord extends TableRecordImpl<PartiteRecord> implements Record9<Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Partite.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Partite.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Partite.postiTotali</code>.
     */
    public void setPostitotali(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Partite.postiTotali</code>.
     */
    public Integer getPostitotali() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Partite.pubblica</code>.
     */
    public void setPubblica(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Partite.pubblica</code>.
     */
    public Integer getPubblica() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Partite.stato</code>.
     */
    public void setStato(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Partite.stato</code>.
     */
    public Integer getStato() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Partite.modPagamento</code>.
     */
    public void setModpagamento(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Partite.modPagamento</code>.
     */
    public String getModpagamento() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Partite.idOrganizzatore</code>.
     */
    public void setIdorganizzatore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Partite.idOrganizzatore</code>.
     */
    public Integer getIdorganizzatore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Partite.idDisponibilita</code>.
     */
    public void setIddisponibilita(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Partite.idDisponibilita</code>.
     */
    public Integer getIddisponibilita() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>Partite.goalSquadraCasa</code>.
     */
    public void setGoalsquadracasa(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Partite.goalSquadraCasa</code>.
     */
    public Integer getGoalsquadracasa() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Partite.goalSquadraTrasferta</code>.
     */
    public void setGoalsquadratrasferta(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Partite.goalSquadraTrasferta</code>.
     */
    public Integer getGoalsquadratrasferta() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Partite.PARTITE.IDPARTITA;
    }

    @Override
    public Field<Integer> field2() {
        return Partite.PARTITE.POSTITOTALI;
    }

    @Override
    public Field<Integer> field3() {
        return Partite.PARTITE.PUBBLICA;
    }

    @Override
    public Field<Integer> field4() {
        return Partite.PARTITE.STATO;
    }

    @Override
    public Field<String> field5() {
        return Partite.PARTITE.MODPAGAMENTO;
    }

    @Override
    public Field<Integer> field6() {
        return Partite.PARTITE.IDORGANIZZATORE;
    }

    @Override
    public Field<Integer> field7() {
        return Partite.PARTITE.IDDISPONIBILITA;
    }

    @Override
    public Field<Integer> field8() {
        return Partite.PARTITE.GOALSQUADRACASA;
    }

    @Override
    public Field<Integer> field9() {
        return Partite.PARTITE.GOALSQUADRATRASFERTA;
    }

    @Override
    public Integer component1() {
        return getIdpartita();
    }

    @Override
    public Integer component2() {
        return getPostitotali();
    }

    @Override
    public Integer component3() {
        return getPubblica();
    }

    @Override
    public Integer component4() {
        return getStato();
    }

    @Override
    public String component5() {
        return getModpagamento();
    }

    @Override
    public Integer component6() {
        return getIdorganizzatore();
    }

    @Override
    public Integer component7() {
        return getIddisponibilita();
    }

    @Override
    public Integer component8() {
        return getGoalsquadracasa();
    }

    @Override
    public Integer component9() {
        return getGoalsquadratrasferta();
    }

    @Override
    public Integer value1() {
        return getIdpartita();
    }

    @Override
    public Integer value2() {
        return getPostitotali();
    }

    @Override
    public Integer value3() {
        return getPubblica();
    }

    @Override
    public Integer value4() {
        return getStato();
    }

    @Override
    public String value5() {
        return getModpagamento();
    }

    @Override
    public Integer value6() {
        return getIdorganizzatore();
    }

    @Override
    public Integer value7() {
        return getIddisponibilita();
    }

    @Override
    public Integer value8() {
        return getGoalsquadracasa();
    }

    @Override
    public Integer value9() {
        return getGoalsquadratrasferta();
    }

    @Override
    public PartiteRecord value1(Integer value) {
        setIdpartita(value);
        return this;
    }

    @Override
    public PartiteRecord value2(Integer value) {
        setPostitotali(value);
        return this;
    }

    @Override
    public PartiteRecord value3(Integer value) {
        setPubblica(value);
        return this;
    }

    @Override
    public PartiteRecord value4(Integer value) {
        setStato(value);
        return this;
    }

    @Override
    public PartiteRecord value5(String value) {
        setModpagamento(value);
        return this;
    }

    @Override
    public PartiteRecord value6(Integer value) {
        setIdorganizzatore(value);
        return this;
    }

    @Override
    public PartiteRecord value7(Integer value) {
        setIddisponibilita(value);
        return this;
    }

    @Override
    public PartiteRecord value8(Integer value) {
        setGoalsquadracasa(value);
        return this;
    }

    @Override
    public PartiteRecord value9(Integer value) {
        setGoalsquadratrasferta(value);
        return this;
    }

    @Override
    public PartiteRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Integer value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartiteRecord
     */
    public PartiteRecord() {
        super(Partite.PARTITE);
    }

    /**
     * Create a detached, initialised PartiteRecord
     */
    public PartiteRecord(Integer idpartita, Integer postitotali, Integer pubblica, Integer stato, String modpagamento, Integer idorganizzatore, Integer iddisponibilita, Integer goalsquadracasa, Integer goalsquadratrasferta) {
        super(Partite.PARTITE);

        setIdpartita(idpartita);
        setPostitotali(postitotali);
        setPubblica(pubblica);
        setStato(stato);
        setModpagamento(modpagamento);
        setIdorganizzatore(idorganizzatore);
        setIddisponibilita(iddisponibilita);
        setGoalsquadracasa(goalsquadracasa);
        setGoalsquadratrasferta(goalsquadratrasferta);
        resetChangedOnNotNull();
    }
}
