/*
 * This file is generated by jOOQ.
 */
package sportmateinc.sportmatebusinesslayergenerated.tables.records;


import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import sportmateinc.sportmatebusinesslayergenerated.tables.Squadre;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SquadreRecord extends TableRecordImpl<SquadreRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Squadre.idSquadra</code>.
     */
    public void setIdsquadra(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Squadre.idSquadra</code>.
     */
    public Integer getIdsquadra() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Squadre.nomeSquadra</code>.
     */
    public void setNomesquadra(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Squadre.nomeSquadra</code>.
     */
    public String getNomesquadra() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Squadre.coloreMaglia</code>.
     */
    public void setColoremaglia(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Squadre.coloreMaglia</code>.
     */
    public String getColoremaglia() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Squadre.inCasa</code>.
     */
    public void setIncasa(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Squadre.inCasa</code>.
     */
    public Integer getIncasa() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Squadre.idPartita</code>.
     */
    public void setIdpartita(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Squadre.idPartita</code>.
     */
    public Integer getIdpartita() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Squadre.SQUADRE.IDSQUADRA;
    }

    @Override
    public Field<String> field2() {
        return Squadre.SQUADRE.NOMESQUADRA;
    }

    @Override
    public Field<String> field3() {
        return Squadre.SQUADRE.COLOREMAGLIA;
    }

    @Override
    public Field<Integer> field4() {
        return Squadre.SQUADRE.INCASA;
    }

    @Override
    public Field<Integer> field5() {
        return Squadre.SQUADRE.IDPARTITA;
    }

    @Override
    public Integer component1() {
        return getIdsquadra();
    }

    @Override
    public String component2() {
        return getNomesquadra();
    }

    @Override
    public String component3() {
        return getColoremaglia();
    }

    @Override
    public Integer component4() {
        return getIncasa();
    }

    @Override
    public Integer component5() {
        return getIdpartita();
    }

    @Override
    public Integer value1() {
        return getIdsquadra();
    }

    @Override
    public String value2() {
        return getNomesquadra();
    }

    @Override
    public String value3() {
        return getColoremaglia();
    }

    @Override
    public Integer value4() {
        return getIncasa();
    }

    @Override
    public Integer value5() {
        return getIdpartita();
    }

    @Override
    public SquadreRecord value1(Integer value) {
        setIdsquadra(value);
        return this;
    }

    @Override
    public SquadreRecord value2(String value) {
        setNomesquadra(value);
        return this;
    }

    @Override
    public SquadreRecord value3(String value) {
        setColoremaglia(value);
        return this;
    }

    @Override
    public SquadreRecord value4(Integer value) {
        setIncasa(value);
        return this;
    }

    @Override
    public SquadreRecord value5(Integer value) {
        setIdpartita(value);
        return this;
    }

    @Override
    public SquadreRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SquadreRecord
     */
    public SquadreRecord() {
        super(Squadre.SQUADRE);
    }

    /**
     * Create a detached, initialised SquadreRecord
     */
    public SquadreRecord(Integer idsquadra, String nomesquadra, String coloremaglia, Integer incasa, Integer idpartita) {
        super(Squadre.SQUADRE);

        setIdsquadra(idsquadra);
        setNomesquadra(nomesquadra);
        setColoremaglia(coloremaglia);
        setIncasa(incasa);
        setIdpartita(idpartita);
        resetChangedOnNotNull();
    }
}
