/*
 * This file is generated by jOOQ.
 */
package sportmateinc.sportmatebusinesslayergenerated.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import sportmateinc.sportmatebusinesslayergenerated.tables.Utenti;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UtentiRecord extends TableRecordImpl<UtentiRecord> implements Record10<Integer, String, String, String, String, String, String, BigDecimal, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Utenti.idUtente</code>.
     */
    public void setIdutente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Utenti.idUtente</code>.
     */
    public Integer getIdutente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Utenti.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Utenti.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Utenti.cognome</code>.
     */
    public void setCognome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Utenti.cognome</code>.
     */
    public String getCognome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Utenti.dataNascita</code>.
     */
    public void setDatanascita(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Utenti.dataNascita</code>.
     */
    public String getDatanascita() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Utenti.mail</code>.
     */
    public void setMail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Utenti.mail</code>.
     */
    public String getMail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Utenti.telefono</code>.
     */
    public void setTelefono(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Utenti.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Utenti.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Utenti.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Utenti.credito</code>.
     */
    public void setCredito(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>Utenti.credito</code>.
     */
    public BigDecimal getCredito() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>Utenti.livello</code>.
     */
    public void setLivello(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Utenti.livello</code>.
     */
    public Integer getLivello() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>Utenti.pathImg</code>.
     */
    public void setPathimg(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>Utenti.pathImg</code>.
     */
    public String getPathimg() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, BigDecimal, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, String, BigDecimal, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Utenti.UTENTI.IDUTENTE;
    }

    @Override
    public Field<String> field2() {
        return Utenti.UTENTI.NOME;
    }

    @Override
    public Field<String> field3() {
        return Utenti.UTENTI.COGNOME;
    }

    @Override
    public Field<String> field4() {
        return Utenti.UTENTI.DATANASCITA;
    }

    @Override
    public Field<String> field5() {
        return Utenti.UTENTI.MAIL;
    }

    @Override
    public Field<String> field6() {
        return Utenti.UTENTI.TELEFONO;
    }

    @Override
    public Field<String> field7() {
        return Utenti.UTENTI.PASSWORD;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Utenti.UTENTI.CREDITO;
    }

    @Override
    public Field<Integer> field9() {
        return Utenti.UTENTI.LIVELLO;
    }

    @Override
    public Field<String> field10() {
        return Utenti.UTENTI.PATHIMG;
    }

    @Override
    public Integer component1() {
        return getIdutente();
    }

    @Override
    public String component2() {
        return getNome();
    }

    @Override
    public String component3() {
        return getCognome();
    }

    @Override
    public String component4() {
        return getDatanascita();
    }

    @Override
    public String component5() {
        return getMail();
    }

    @Override
    public String component6() {
        return getTelefono();
    }

    @Override
    public String component7() {
        return getPassword();
    }

    @Override
    public BigDecimal component8() {
        return getCredito();
    }

    @Override
    public Integer component9() {
        return getLivello();
    }

    @Override
    public String component10() {
        return getPathimg();
    }

    @Override
    public Integer value1() {
        return getIdutente();
    }

    @Override
    public String value2() {
        return getNome();
    }

    @Override
    public String value3() {
        return getCognome();
    }

    @Override
    public String value4() {
        return getDatanascita();
    }

    @Override
    public String value5() {
        return getMail();
    }

    @Override
    public String value6() {
        return getTelefono();
    }

    @Override
    public String value7() {
        return getPassword();
    }

    @Override
    public BigDecimal value8() {
        return getCredito();
    }

    @Override
    public Integer value9() {
        return getLivello();
    }

    @Override
    public String value10() {
        return getPathimg();
    }

    @Override
    public UtentiRecord value1(Integer value) {
        setIdutente(value);
        return this;
    }

    @Override
    public UtentiRecord value2(String value) {
        setNome(value);
        return this;
    }

    @Override
    public UtentiRecord value3(String value) {
        setCognome(value);
        return this;
    }

    @Override
    public UtentiRecord value4(String value) {
        setDatanascita(value);
        return this;
    }

    @Override
    public UtentiRecord value5(String value) {
        setMail(value);
        return this;
    }

    @Override
    public UtentiRecord value6(String value) {
        setTelefono(value);
        return this;
    }

    @Override
    public UtentiRecord value7(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UtentiRecord value8(BigDecimal value) {
        setCredito(value);
        return this;
    }

    @Override
    public UtentiRecord value9(Integer value) {
        setLivello(value);
        return this;
    }

    @Override
    public UtentiRecord value10(String value) {
        setPathimg(value);
        return this;
    }

    @Override
    public UtentiRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, BigDecimal value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UtentiRecord
     */
    public UtentiRecord() {
        super(Utenti.UTENTI);
    }

    /**
     * Create a detached, initialised UtentiRecord
     */
    public UtentiRecord(Integer idutente, String nome, String cognome, String datanascita, String mail, String telefono, String password, BigDecimal credito, Integer livello, String pathimg) {
        super(Utenti.UTENTI);

        setIdutente(idutente);
        setNome(nome);
        setCognome(cognome);
        setDatanascita(datanascita);
        setMail(mail);
        setTelefono(telefono);
        setPassword(password);
        setCredito(credito);
        setLivello(livello);
        setPathimg(pathimg);
        resetChangedOnNotNull();
    }
}
