/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.DettagliotipologiecentriRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dettagliotipologiecentri extends TableImpl<DettagliotipologiecentriRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DettaglioTipologieCentri</code>
     */
    public static final Dettagliotipologiecentri DETTAGLIOTIPOLOGIECENTRI = new Dettagliotipologiecentri();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DettagliotipologiecentriRecord> getRecordType() {
        return DettagliotipologiecentriRecord.class;
    }

    /**
     * The column <code>DettaglioTipologieCentri.idCentro</code>.
     */
    public final TableField<DettagliotipologiecentriRecord, Integer> IDCENTRO = createField(DSL.name("idCentro"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DettaglioTipologieCentri.idTipologia</code>.
     */
    public final TableField<DettagliotipologiecentriRecord, Integer> IDTIPOLOGIA = createField(DSL.name("idTipologia"), SQLDataType.INTEGER, this, "");

    private Dettagliotipologiecentri(Name alias, Table<DettagliotipologiecentriRecord> aliased) {
        this(alias, aliased, null);
    }

    private Dettagliotipologiecentri(Name alias, Table<DettagliotipologiecentriRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri(String alias) {
        this(DSL.name(alias), DETTAGLIOTIPOLOGIECENTRI);
    }

    /**
     * Create an aliased <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri(Name alias) {
        this(alias, DETTAGLIOTIPOLOGIECENTRI);
    }

    /**
     * Create a <code>DettaglioTipologieCentri</code> table reference
     */
    public Dettagliotipologiecentri() {
        this(DSL.name("DettaglioTipologieCentri"), null);
    }

    public <O extends Record> Dettagliotipologiecentri(Table<O> child, ForeignKey<O, DettagliotipologiecentriRecord> key) {
        super(child, key, DETTAGLIOTIPOLOGIECENTRI);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Dettagliotipologiecentri as(String alias) {
        return new Dettagliotipologiecentri(DSL.name(alias), this);
    }

    @Override
    public Dettagliotipologiecentri as(Name alias) {
        return new Dettagliotipologiecentri(alias, this);
    }

    @Override
    public Dettagliotipologiecentri as(Table<?> alias) {
        return new Dettagliotipologiecentri(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(String name) {
        return new Dettagliotipologiecentri(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(Name name) {
        return new Dettagliotipologiecentri(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dettagliotipologiecentri rename(Table<?> name) {
        return new Dettagliotipologiecentri(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
