/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.DisponibilitaRecord;

import java.math.BigDecimal;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Disponibilita extends TableImpl<DisponibilitaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Disponibilita</code>
     */
    public static final Disponibilita DISPONIBILITA = new Disponibilita();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DisponibilitaRecord> getRecordType() {
        return DisponibilitaRecord.class;
    }

    /**
     * The column <code>Disponibilita.idDisponibilita</code>.
     */
    public final TableField<DisponibilitaRecord, Integer> IDDISPONIBILITA = createField(DSL.name("idDisponibilita"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Disponibilita.dataOra</code>.
     */
    public final TableField<DisponibilitaRecord, String> DATAORA = createField(DSL.name("dataOra"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Disponibilita.prezzo</code>.
     */
    public final TableField<DisponibilitaRecord, BigDecimal> PREZZO = createField(DSL.name("prezzo"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>Disponibilita.tipoCampo</code>.
     */
    public final TableField<DisponibilitaRecord, Integer> TIPOCAMPO = createField(DSL.name("tipoCampo"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Disponibilita.idCentro</code>.
     */
    public final TableField<DisponibilitaRecord, Integer> IDCENTRO = createField(DSL.name("idCentro"), SQLDataType.INTEGER.nullable(false), this, "");

    private Disponibilita(Name alias, Table<DisponibilitaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Disponibilita(Name alias, Table<DisponibilitaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Disponibilita</code> table reference
     */
    public Disponibilita(String alias) {
        this(DSL.name(alias), DISPONIBILITA);
    }

    /**
     * Create an aliased <code>Disponibilita</code> table reference
     */
    public Disponibilita(Name alias) {
        this(alias, DISPONIBILITA);
    }

    /**
     * Create a <code>Disponibilita</code> table reference
     */
    public Disponibilita() {
        this(DSL.name("Disponibilita"), null);
    }

    public <O extends Record> Disponibilita(Table<O> child, ForeignKey<O, DisponibilitaRecord> key) {
        super(child, key, DISPONIBILITA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Disponibilita as(String alias) {
        return new Disponibilita(DSL.name(alias), this);
    }

    @Override
    public Disponibilita as(Name alias) {
        return new Disponibilita(alias, this);
    }

    @Override
    public Disponibilita as(Table<?> alias) {
        return new Disponibilita(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Disponibilita rename(String name) {
        return new Disponibilita(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Disponibilita rename(Name name) {
        return new Disponibilita(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Disponibilita rename(Table<?> name) {
        return new Disponibilita(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, BigDecimal, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super BigDecimal, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super BigDecimal, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
