/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.MessaggiorgfinRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messaggiorgfin extends TableImpl<MessaggiorgfinRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MessaggiOrgFin</code>
     */
    public static final Messaggiorgfin MESSAGGIORGFIN = new Messaggiorgfin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessaggiorgfinRecord> getRecordType() {
        return MessaggiorgfinRecord.class;
    }

    /**
     * The column <code>MessaggiOrgFin.idMessaggio</code>.
     */
    public final TableField<MessaggiorgfinRecord, Integer> IDMESSAGGIO = createField(DSL.name("idMessaggio"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MessaggiOrgFin.stato</code>.
     */
    public final TableField<MessaggiorgfinRecord, Integer> STATO = createField(DSL.name("stato"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MessaggiOrgFin.testo</code>.
     */
    public final TableField<MessaggiorgfinRecord, String> TESTO = createField(DSL.name("testo"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>MessaggiOrgFin.dataOra</code>.
     */
    public final TableField<MessaggiorgfinRecord, String> DATAORA = createField(DSL.name("dataOra"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>MessaggiOrgFin.idOrganizzatore</code>.
     */
    public final TableField<MessaggiorgfinRecord, Integer> IDORGANIZZATORE = createField(DSL.name("idOrganizzatore"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MessaggiOrgFin.idUtenteFinale</code>.
     */
    public final TableField<MessaggiorgfinRecord, Integer> IDUTENTEFINALE = createField(DSL.name("idUtenteFinale"), SQLDataType.INTEGER.nullable(false), this, "");

    private Messaggiorgfin(Name alias, Table<MessaggiorgfinRecord> aliased) {
        this(alias, aliased, null);
    }

    private Messaggiorgfin(Name alias, Table<MessaggiorgfinRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>MessaggiOrgFin</code> table reference
     */
    public Messaggiorgfin(String alias) {
        this(DSL.name(alias), MESSAGGIORGFIN);
    }

    /**
     * Create an aliased <code>MessaggiOrgFin</code> table reference
     */
    public Messaggiorgfin(Name alias) {
        this(alias, MESSAGGIORGFIN);
    }

    /**
     * Create a <code>MessaggiOrgFin</code> table reference
     */
    public Messaggiorgfin() {
        this(DSL.name("MessaggiOrgFin"), null);
    }

    public <O extends Record> Messaggiorgfin(Table<O> child, ForeignKey<O, MessaggiorgfinRecord> key) {
        super(child, key, MESSAGGIORGFIN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Messaggiorgfin as(String alias) {
        return new Messaggiorgfin(DSL.name(alias), this);
    }

    @Override
    public Messaggiorgfin as(Name alias) {
        return new Messaggiorgfin(alias, this);
    }

    @Override
    public Messaggiorgfin as(Table<?> alias) {
        return new Messaggiorgfin(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggiorgfin rename(String name) {
        return new Messaggiorgfin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggiorgfin rename(Name name) {
        return new Messaggiorgfin(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messaggiorgfin rename(Table<?> name) {
        return new Messaggiorgfin(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super Integer, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super Integer, ? super String, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
