/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.TipologiecampoRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tipologiecampo extends TableImpl<TipologiecampoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TipologieCampo</code>
     */
    public static final Tipologiecampo TIPOLOGIECAMPO = new Tipologiecampo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TipologiecampoRecord> getRecordType() {
        return TipologiecampoRecord.class;
    }

    /**
     * The column <code>TipologieCampo.idTipologia</code>.
     */
    public final TableField<TipologiecampoRecord, Integer> IDTIPOLOGIA = createField(DSL.name("idTipologia"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TipologieCampo.nomeTipologia</code>.
     */
    public final TableField<TipologiecampoRecord, String> NOMETIPOLOGIA = createField(DSL.name("nomeTipologia"), SQLDataType.CLOB.nullable(false), this, "");

    private Tipologiecampo(Name alias, Table<TipologiecampoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tipologiecampo(Name alias, Table<TipologiecampoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo(String alias) {
        this(DSL.name(alias), TIPOLOGIECAMPO);
    }

    /**
     * Create an aliased <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo(Name alias) {
        this(alias, TIPOLOGIECAMPO);
    }

    /**
     * Create a <code>TipologieCampo</code> table reference
     */
    public Tipologiecampo() {
        this(DSL.name("TipologieCampo"), null);
    }

    public <O extends Record> Tipologiecampo(Table<O> child, ForeignKey<O, TipologiecampoRecord> key) {
        super(child, key, TIPOLOGIECAMPO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Tipologiecampo as(String alias) {
        return new Tipologiecampo(DSL.name(alias), this);
    }

    @Override
    public Tipologiecampo as(Name alias) {
        return new Tipologiecampo(alias, this);
    }

    @Override
    public Tipologiecampo as(Table<?> alias) {
        return new Tipologiecampo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(String name) {
        return new Tipologiecampo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(Name name) {
        return new Tipologiecampo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tipologiecampo rename(Table<?> name) {
        return new Tipologiecampo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
