/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.TransazioniRecord;

import java.math.BigDecimal;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Transazioni extends TableImpl<TransazioniRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Transazioni</code>
     */
    public static final Transazioni TRANSAZIONI = new Transazioni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransazioniRecord> getRecordType() {
        return TransazioniRecord.class;
    }

    /**
     * The column <code>Transazioni.idTransazione</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDTRANSAZIONE = createField(DSL.name("idTransazione"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>Transazioni.importo</code>.
     */
    public final TableField<TransazioniRecord, BigDecimal> IMPORTO = createField(DSL.name("importo"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>Transazioni.data</code>.
     */
    public final TableField<TransazioniRecord, String> DATA = createField(DSL.name("data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Transazioni.idPartita</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDPARTITA = createField(DSL.name("idPartita"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Transazioni.idUtente</code>.
     */
    public final TableField<TransazioniRecord, Integer> IDUTENTE = createField(DSL.name("idUtente"), SQLDataType.INTEGER.nullable(false), this, "");

    private Transazioni(Name alias, Table<TransazioniRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transazioni(Name alias, Table<TransazioniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Transazioni</code> table reference
     */
    public Transazioni(String alias) {
        this(DSL.name(alias), TRANSAZIONI);
    }

    /**
     * Create an aliased <code>Transazioni</code> table reference
     */
    public Transazioni(Name alias) {
        this(alias, TRANSAZIONI);
    }

    /**
     * Create a <code>Transazioni</code> table reference
     */
    public Transazioni() {
        this(DSL.name("Transazioni"), null);
    }

    public <O extends Record> Transazioni(Table<O> child, ForeignKey<O, TransazioniRecord> key) {
        super(child, key, TRANSAZIONI);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<TransazioniRecord, Integer> getIdentity() {
        return (Identity<TransazioniRecord, Integer>) super.getIdentity();
    }

    @Override
    public Transazioni as(String alias) {
        return new Transazioni(DSL.name(alias), this);
    }

    @Override
    public Transazioni as(Name alias) {
        return new Transazioni(alias, this);
    }

    @Override
    public Transazioni as(Table<?> alias) {
        return new Transazioni(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(String name) {
        return new Transazioni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(Name name) {
        return new Transazioni(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transazioni rename(Table<?> name) {
        return new Transazioni(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, BigDecimal, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super BigDecimal, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super BigDecimal, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
