/*
 * This file is generated by jOOQ.
 */
package SportMateInc.SportMateBusinessLayer.tables;


import SportMateInc.SportMateBusinessLayer.DefaultSchema;
import SportMateInc.SportMateBusinessLayer.tables.records.UtentiRecord;

import java.math.BigDecimal;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Utenti extends TableImpl<UtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Utenti</code>
     */
    public static final Utenti UTENTI = new Utenti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtentiRecord> getRecordType() {
        return UtentiRecord.class;
    }

    /**
     * The column <code>Utenti.idUtente</code>.
     */
    public final TableField<UtentiRecord, Integer> IDUTENTE = createField(DSL.name("idUtente"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Utenti.nome</code>.
     */
    public final TableField<UtentiRecord, String> NOME = createField(DSL.name("nome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.cognome</code>.
     */
    public final TableField<UtentiRecord, String> COGNOME = createField(DSL.name("cognome"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.dataNascita</code>.
     */
    public final TableField<UtentiRecord, String> DATANASCITA = createField(DSL.name("dataNascita"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.mail</code>.
     */
    public final TableField<UtentiRecord, String> MAIL = createField(DSL.name("mail"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.telefono</code>.
     */
    public final TableField<UtentiRecord, String> TELEFONO = createField(DSL.name("telefono"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Utenti.password</code>.
     */
    public final TableField<UtentiRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Utenti.credito</code>.
     */
    public final TableField<UtentiRecord, BigDecimal> CREDITO = createField(DSL.name("credito"), SQLDataType.NUMERIC.nullable(false).defaultValue(DSL.field(DSL.raw("10"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>Utenti.livello</code>.
     */
    public final TableField<UtentiRecord, Integer> LIVELLO = createField(DSL.name("livello"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>Utenti.pathImg</code>.
     */
    public final TableField<UtentiRecord, String> PATHIMG = createField(DSL.name("pathImg"), SQLDataType.CLOB, this, "");

    private Utenti(Name alias, Table<UtentiRecord> aliased) {
        this(alias, aliased, null);
    }

    private Utenti(Name alias, Table<UtentiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Utenti</code> table reference
     */
    public Utenti(String alias) {
        this(DSL.name(alias), UTENTI);
    }

    /**
     * Create an aliased <code>Utenti</code> table reference
     */
    public Utenti(Name alias) {
        this(alias, UTENTI);
    }

    /**
     * Create a <code>Utenti</code> table reference
     */
    public Utenti() {
        this(DSL.name("Utenti"), null);
    }

    public <O extends Record> Utenti(Table<O> child, ForeignKey<O, UtentiRecord> key) {
        super(child, key, UTENTI);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Utenti as(String alias) {
        return new Utenti(DSL.name(alias), this);
    }

    @Override
    public Utenti as(Name alias) {
        return new Utenti(alias, this);
    }

    @Override
    public Utenti as(Table<?> alias) {
        return new Utenti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(String name) {
        return new Utenti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Name name) {
        return new Utenti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Table<?> name) {
        return new Utenti(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, BigDecimal, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super BigDecimal, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super BigDecimal, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
