name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and Install SportMateDBLayer
        run: mvn clean install --file ./Codice/SportMateDBLayer/pom.xml
      - name: Build and Install SportMateBusinessLayer
        run: mvn clean install --file ./Codice/SportMateBusinessLayer/pom.xml
      - name: Build SportMatePresentationLayer
        run: mvn package --file ./Codice/SportMatePresentationLayer/pom.xml

