name: CI/CD
on:
  push:
    branches: [ "main" ]
   # paths: ["Codice/**"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  call-SportMateDBLayerMaven:
    uses: ./.github/workflows/SportMateDBLayerMaven.yml
  call-SportMateBusinessLayerMaven:
    if: ${{ always() }}
    needs: call-SportMateDBLayerMaven
    uses: ./.github/workflows/SportMateBusinessLayerMaven.yml
  call-SportMatePresentationLayerMaven:
    if: ${{ always() }}
    needs: call-SportMateBusinessLayerMaven
    uses: ./.github/workflows/SportMatePresentationLayerMaven.yml
